version: "2.4"

services:
  dataverse:
    container_name: "prod_dataverse"
    hostname: dataverse
    image: ${APP_IMAGE}
    restart: on-failure
    user: payara
    environment:
      DATAVERSE_DB_HOST: postgres
      DATAVERSE_DB_PASSWORD: ${DB_PASSWORD}
      DATAVERSE_DB_USER: ${DATAVERSE_DB_USER}
      ENABLE_JDWP: "1"
      ENABLE_RELOAD: "1"
      SKIP_DEPLOY: "${SKIP_DEPLOY}"
      DATAVERSE_MAIL_SYSTEM_EMAIL: ${MAIL_SYSTEM_EMAIL}
      DATAVERSE_MAIL_MTA_HOST: ${MAIL_HOST}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      SITE_URL: ${SITE_URL}
      DATAVERSE_JSF_REFRESH_PERIOD: "1"
      DATAVERSE_FEATURE_API_BEARER_AUTH: "1"
      DATAVERSE_AUTH_OIDC_ENABLED: ${OIDC_ENABLED:-0}
      DATAVERSE_SPI_EXPORTERS_DIRECTORY: "/dv/exporters"
      JVM_ARGS: -Ddataverse.files.storage-driver-id=file1
        -Ddataverse.files.file1.type=file
        -Ddataverse.files.file1.label=Filesystem
        -Ddataverse.files.file1.directory=/data/store
        -Ddataverse.pid.providers=fake
        -Ddataverse.pid.default-provider=fake
        -Ddataverse.pid.fake.type=FAKE
        -Ddataverse.pid.fake.label=FakeDOIProvider
        -Ddataverse.pid.fake.authority=10.5072
        -Ddataverse.pid.fake.shoulder=FK2/
        -Ddataverse.lang.directory=/dv/lang
    ports:
      # - "8080:8080"
      - "4848:4848" # Add admin console port
      - "9009:9009"
    networks:
      - dataverse
    depends_on:
      - postgres
      - solr
    volumes:
      - dataverse_data:/dv
      - dataverse_secrets:/secrets
      - storage_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/info/version"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 60s
    mem_limit: 4g
    mem_reservation: 2g

  postgres:
    container_name: "prod_postgres"
    hostname: postgres
    image: postgres:${POSTGRES_VERSION}
    restart: on-failure
    environment:
      - POSTGRES_USER=${DATAVERSE_DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - dataverse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATAVERSE_DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  solr:
    container_name: "prod_solr"
    hostname: "solr"
    image: solr:${SOLR_VERSION}
    restart: on-failure
    command:
      - "solr-precreate"
      - "collection1"
      - "/template"
    networks:
      - dataverse
    volumes:
      - solr_data:/var/solr
      - solr_conf:/template
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/"]
      interval: 10s
      timeout: 5s
      retries: 5

  smtp:
    container_name: "prod_smtp"
    hostname: "smtp"
    image: maildev/maildev:2.0.5 # For production, replace with your actual SMTP server
    restart: on-failure
    networks:
      - dataverse

  webserver:
    container_name: "prod_nginx"
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - dataverse
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - dataverse

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

networks:
  dataverse:
    name: dataverse_network
    driver: bridge

volumes:
  dataverse_data:
  dataverse_secrets:
  storage_data:
  postgres_data:
  solr_data:
  solr_conf:
