name: Dataverse CI/CD

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -Pct clean package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/dataverse:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            cd ~/Documents/dataverse
            
            # Create or update .env file
            cat << EOF > .env
            APP_IMAGE=${{ secrets.DOCKER_USERNAME }}/dataverse:latest
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DATAVERSE_DB_USER=${{ secrets.DATAVERSE_DB_USER }}
            MAIL_SYSTEM_EMAIL=${{ secrets.MAIL_SYSTEM_EMAIL }}
            MAIL_HOST=${{ secrets.MAIL_HOST }}
            EOF
            
            # Pull latest images and restart containers
            docker-compose -f docker-compose-prod.yml pull
            docker-compose -f docker-compose-prod.yml down
            docker-compose -f docker-compose-prod.yml up -d
            
            # Wait for services to be healthy
            sleep 30
            
            # Optional: Check if services are running
            docker-compose -f docker-compose-prod.yml ps